### ISSUE TITLE
allow_game_relative_writes won't overwrite an existing file even if removed before write.

### ISSUE THREAD

**Issue by jnackmclain** [xenia-canary/xenia-canary#123]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

I am working on a mod for a game that will be saving custom information on disk. On console, I can generate a new file as long as I delete the file beforehand. In xenia, even if I delete the file first, a new file will not be generated. This behavior also extends if the file exists on disk when I boot the game, (assuming mounted to game: at runtime) I have to close xenia and relaunch the game to generate a new file from within the game.

https://user-images.githubusercontent.com/55568980/216476782-96b95705-5b1e-4efa-817a-49eb99079b74.mp4

### Describe what should happen

since I deleted the file, on the disk, the game should be able to write to that file again without the game being relaunched, thus remounting game:

**Comment by AdrianCassar** [comment]
I can replicate this bug the problem resides in [VirtualFileSystem::OpenFile](https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/src/xenia/vfs/virtual_file_system.cc#L180).

This problem occurs due to caching file entries in the virtual filesystem. The cached file entries are not automatically updated when a file/directory is deleted from the host. Due to this the next file creation/open attempt is unsuccessful because of the already existing entry.

A potential solution is to check if the file entry exists on the host before creation, if not then remove the entry from the virtual filesystem device.

**Comment by jnackmclain** [comment]
Unfortunately I don't have a way to delete files from the disk from within the game, only create and read.

**Comment by ghost** [comment]
allow_game_relative_writes when it was added was only intended to be used to generate data from guest code to be compared against data generated the same way on real hardware, it only had to be done once to generate the file which is probably how this slipped through the cracks. unless someone is willing to fix this on the VFS side maybe the name of the cvar should be changed in the meantime to better reflect what it can do.

**Comment by AdrianCassar** [comment]
I'm not sure if this will fix the problem with the already existent file on startup. However it should fix the problem of generating the file during runtime if deleted from the host. If you could test the PR that would be great.

**Comment by jnackmclain** [comment]
Will test when build finishes, thank you very much

**Comment by jnackmclain** [comment]
@AdrianCassar It's definitely a different behavior, but not quite perfect.
So the first write I do from the game will save a file and include the proper contents. However if I delete my generated file, and try to generate a new one, the game still sees the file is there (game code runs a file_exists check to get this warning)

As well, a second generated file after deleting the original generated file will come out empty. I have tested on real hardware and the game will write the proper info after deleting the original generated file.


https://user-images.githubusercontent.com/55568980/216782280-eb5fe8df-12d1-4bd6-ad48-f4d60cc3466c.mp4

**Comment by AdrianCassar** [comment]
Thanks for the feedback, i unfortunately cannot reproduce this since i don't have UI feedback from the game i'm testing with stating the existence of the file. Although i suspect it's due to the cached entry still existing when `file_exists` is checked. In addition, in my scenario when the file is regenerated it contains content.

**Comment by jnackmclain** [comment]
if you like, you can build this from our repo, it does require the base game to function, but the write settings handle is live. I'll continue messing with it and see if i can get it to output content again, thank you very much for the help!
https://github.com/hmxmilohax/rock-band-3-deluxe

**Comment by AdrianCassar** [comment]
I have resolved the problem and updated the PR, the issue occurred as suspected due to `file_exists`. It would open the file to check for existence and then it would forcefully create the file if it was not found on the host system (current solution).  As a result, creating an empty file by force and not returning `X_STATUS_NO_SUCH_FILE` as desired. Subsequently cancelling the following function call to write the content.

**Comment by jnackmclain** [comment]
I can confirm this PR resolves the issue in my setup, thank you very much!
