### ISSUE TITLE
Brightness/Gamma settings in Project Gotham Racing 4 seem broken. Game is too dark.

### ISSUE THREAD

**Issue by gutibroker** [xenia-canary/xenia-canary#161]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Game appears too dark on my main PC (intel 9900k + 3080 rtx). Seems as if gamma/brigthness settings are broken and game does not have in game brightness or contrast settings. 

PGR 3 and other games look fine. 

I tried changing some settings in config file like gamma / sRGB etc, but game looks the same. 

Also, the game looks fine in other pcs i tried (a laptop with iris graphics and steam deck)

### Describe what should happen

Game should have proper colors/gamma and not appear dark.

**Comment by Rombbb** [comment]
Not sure why this bug report was marked as invalid, because I have 100% the same thing on a 10900k / 3090 RTX

Fix I found is to change render path from rtv to rov, but drawback is that it creates some slowdowns.

Anyhow for sure with default settings, i.e. rtv, OP is right, the games lighting is bugged and way too dark

**Comment by Margen67** [comment]
> Not sure why this bug report was marked as invalid, because I have 100% the same thing on a 10900k / 3090 RTX
> 
> Fix I found is to change render path from rtv to rov, but drawback is that it creates some slowdowns.
> 
> Anyhow for sure with default settings, i.e. rtv, OP is right, the games lighting is bugged and way too dark

Does this happen on master?

**Comment by Rombbb** [comment]
> Does this happen on master?

same dark color on master and canary, only difference is that with canary there is somewhat of a workaround by using rov i.o. rtv in config file (although it really isnt that smooth and playable with rov), while for master I guess this workaround would work as well but couldn't test as the game crashes on startup when changing rtv to rov.

Win 11 / 10900k / 32 DDR4 / 3090 rtx / SSD

**Comment by Rombbb** [comment]
testing a bit further and with ROV the sky is actually over-bright  sometimes (plus it runs bad compared to RTV)

Will stick with RTV, maybe it is just how the game is and not the emulator, maybe marking this topic as Invalid was correct after all.

No idea :-) 

Although I did encounter several tracks with skyboxes where everything just felt really mat, dark and incorrect

Will be upping playthrough episodes on Rombbb Gaming YT channel in a day or two, so if handy the color tone can be checked out there.

Thanks and if indeed its how the game is supposed to be, sorry for wasting your time with reviving this thread.

**Comment by Rombbb** [comment]
Did some further testing because lighting imo is such a huge part of this game (they really nailed that in the original games) and there is indeed noticeable difference between default RTV and ROV.

With RTV any light sources dont seem to emit light, the colors are there but the vibrancy not, it's muted and bland.
(I'm nottalking about saturation, I hate over-saturated games, it really is about light sources not appearing as such, not being brighter than non-light sources).

ROV fixes it, although initially due to perfomance impact it was not playable, however after messing about, hard capping fps to 30 in Nvidia control panel with vsync off, DSR x2.25, MSAA x8 is smooth and playable with super lighting :-)

For anyone interested.

Comparison is visible on Rombbb Gaming on YT, PGR4 Playthrough, ep. 1 to 8 is bad, dark lighting, from ep.9 nice lighting.

**Comment by KingLich1** [comment]
This game is definitely WAY too dark in this emulator, i can barely see where I'm going, plus the car's back and front lights just don't work i think.

**Comment by Rombbb** [comment]
in config set 'render_target_path_d3d12' from rtv to rov
has performance impact because it is experimental or something (draws all kind of needless stuff offsscreen) but if you have a deccent pc and cap framerate in nvidia control panel to 30fps then it works fine, with ok lighting.
Lighting is huge in this game so I prefer it over fps

    On Sunday, January 14, 2024 at 10:40:28 AM GMT+1, KingLich1 ***@***.***> wrote:  
 
 


This game is definitely WAY too dark in this emulator, i can barely see where I'm going, plus the car's back and front lights just don't work i think.
