### ISSUE TITLE
I have a similar error that occurs:

### ISSUE THREAD

**Issue by Shyyguyymusiq** [xenia-canary/xenia-canary#252]
Fallout New Vegas unhandled expectation error: 
![image](https://user-images.githubusercontent.com/80211714/229946204-5accbd0a-3faf-4ae7-8f1e-6028f9643af4.png)
[xenia.log](https://github.com/xenia-canary/xenia-canary/files/11153995/xenia.log)

In this case, it occurs is after launching RDR an only at the main menu.

_Originally posted by @WesternGamer in https://github.com/xenia-canary/xenia-canary/issues/143#issuecomment-1496730619_

**Comment by Shyyguyymusiq** [comment]
Someone please help me find a fix!!! Same error different game

**Comment by Gliniak** [comment]
First thing. Update your emulator version. It might fix it.

Second thing. There is missing audio device in your system which prevents correct initialization.
``!> 0000228C IXAudio2::CreateMasteringVoice failed with 0x-7776FFFF``

Third thing. It after dealing with previous steps you still gonna have: ``C> 01000008 Execute(82C261F0): failed to find function`` or something similar in log then your game dump is corrupted and you have to redump it.

**Comment by rroginela** [comment]
HI,

Have this running perfect CI7-9700/16GBR/AMDRX580 30-40fps make sure to get the game patches from https://github.com/xenia-canary/game-patches and use the latest build of canary (I do, the one from 12/23) I get a rock steady 36-40Fps (heheh rock steady). Nothing special besides that I'll include my conf file that runs the game well and consistently for 2-3hrs (all I get :( ). Your milage may vary but hopefully this helps! Check out https://www.reddit.com/r/ProjectForzaPlus/comments/11a4qus/welcome_to_the_project_forza_plus_sub/ for a really well documented setup for xenia it helped me learn some of the xenia ropes. 

Rename the conf file if you want to use as is or try to match up the settings to your conf file.... I store conf file with the game since a lot of the better games require special settings that may bork other games. Once I find a perfect setup I stop and copy the conf file to the game dir. Reddit/YouTube and Discord are your best sources of information and help (Especially Discord based on all the success stories on Reddit)

If your computer is capable of running this game emulated then the game will run (perfectish, even the original game on the 360 actual hardware would crash sometimes or bork or get stuck, very rarely I had over 1k of hours in the OG game on the OG360 and the One). Love being able to play it again it is awesome and so much better than the new one (Opinion, could be wrong :).

 Good luck enjoy! 
[RDR_xenia-canary.config.toml.txt](https://github.com/xenia-canary/xenia-canary/files/13783255/RDR_xenia-canary.config.toml.txt)
