### ISSUE TITLE
Xbox 360 Blades Dashboard Doesn't Work

### ISSUE THREAD

**Issue by FastMaster678** [xenia-canary/xenia-canary#43]
Hello! I downloaded a zip folder that contains the 1888 version of the Xbox 360 "Blades" dashboard. I also downloaded a zip that contains the update files. According to some tutorials I then watched, I got xextool and used Git Bash to extract the update files to the dashboard folder. Afterward, you're supposed to take the file called "dash.xex" and open it with a certain version of Xenia Canary.
I tried opening it normally inside Xenia Canary and in Windows Explorer, and I also tried Drag-And-Drop. But Xenia Canary says "Uh-oh! Xenia has crashed" or a popup saying "xenia-canary.exe has stopped working" or a black screen with Xenia Canary running at 0 fps. It _does_ say it's running the dashboard, though.

Any help would be much appreciated! Thank you!

**Comment by FastMaster678** [comment]
BTW, I tried the latest version of Canary and three releases from 2020.

**Comment by halotroop2288** [comment]
> I got xextool and used Git Bash to extract the update files to the dashboard folder.

Were you by any chance watching my tutorial? Git bash is not a requirement. I just used it because it's a quick way to open the terminal. You can use Windows Command Prompt (cmd.exe) or Powershell as well.

Your problem is probably that you're using the wrong build.

You currently must have a very specific build of Canary to run any version of the Dashboard other than 2.0.6XXX.0 versions, or a custom build. This is the same as Master. @Gliniak  is currently working on creating a new build of Canary that will (hopefully) support as much as the old build.

**Comment by FastMaster678** [comment]
OK, thank you!
